#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker images
docker tag feed-api $DOCKER_USERNAME/feed-api
docker tag users-api $DOCKER_USERNAME/users-api

docker push $DOCKER_USERNAME/feed-api
docker push $DOCKER_USERNAME/users-api
